### ISSUE TITLE
请教运行问题

### ISSUE THREAD

**Issue by onedayday-wb** [chenyifanthu/WechatAnnualReport#1]
```
D:/DevelopmentTools/JetBrainsProjects/PycharmProjects/WechatAnnualReport/GenerateReport.py
D:\DevelopmentTools\JetBrainsProjects\PycharmProjects\WechatAnnualReport\GenerateReport.py:36: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  contacts = pd.read_csv(contacts_file, index_col=False)
Traceback (most recent call last):
  File "D:\DevelopmentTools\JetBrainsProjects\PycharmProjects\WechatAnnualReport\GenerateReport.py", line 237, in <module>
    contacts, messages = load_info()
  File "D:\DevelopmentTools\JetBrainsProjects\PycharmProjects\WechatAnnualReport\GenerateReport.py", line 41, in load_info
    messages["isGroup"] = messages["NickName"].apply(lambda x: isgroup[x])
  File "D:\DevelopmentTools\JetBrainsProjects\PycharmProjects\WechatAnnualReport\.env\lib\site-packages\pandas\core\series.py", line 4757, in apply
    return SeriesApply(
  File "D:\DevelopmentTools\JetBrainsProjects\PycharmProjects\WechatAnnualReport\.env\lib\site-packages\pandas\core\apply.py", line 1209, in apply
    return self.apply_standard()
  File "D:\DevelopmentTools\JetBrainsProjects\PycharmProjects\WechatAnnualReport\.env\lib\site-packages\pandas\core\apply.py", line 1289, in apply_standard
    mapped = obj._map_values(
  File "D:\DevelopmentTools\JetBrainsProjects\PycharmProjects\WechatAnnualReport\.env\lib\site-packages\pandas\core\base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
  File "D:\DevelopmentTools\JetBrainsProjects\PycharmProjects\WechatAnnualReport\.env\lib\site-packages\pandas\core\algorithms.py", line 1814, in map_array
    return lib.map_infer(values, mapper, convert=convert)
  File "lib.pyx", line 2926, in pandas._libs.lib.map_infer
  File "D:\DevelopmentTools\JetBrainsProjects\PycharmProjects\WechatAnnualReport\GenerateReport.py", line 41, in <lambda>
    messages["isGroup"] = messages["NickName"].apply(lambda x: isgroup[x])
KeyError: nan

Process finished with exit code 1
```

一运行就这样了，数据不匹配是怎么样一个不匹配啊

**Comment by MYSKY-github** [comment]
me 2

**Comment by xiac20** [comment]
the same problem

**Comment by xiac20** [comment]
hello, I sloved the problem.
Maybe you can add 'isgroup['nan']=False' before it.
