### ISSUE TITLE
Failed to deal with messages with "微信团队"

### ISSUE THREAD

**Issue by SphenHe** [chenyifanthu/WechatAnnualReport#4]
When I tried to run this program, it crashed beacuse it failed to deal with messages with "微信团队". Luckily, just **deleting messages containing "微信团队" in "messages.csv"** can solve this problem. 

and this is the output in my terminal:

```
PS C:\Users\admin\Desktop\wechat\WechatAnnualReport> python .\GenerateReport.py
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\wechat\WechatAnnualReport\GenerateReport.py", line 226, in <module>
    contacts, messages = load_info()
                         ^^^^^^^^^^^
  File "C:\Users\admin\Desktop\wechat\WechatAnnualReport\preprocess.py", line 46, in load_info
    messages["isGroup"] = messages["NickName"].apply(lambda x: isgroup[x])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\series.py", line 4760, in apply
    ).apply()
      ^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 1207, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\apply.py", line 1287, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\algorithms.py", line 1814, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2917, in pandas._libs.lib.map_infer
  File "C:\Users\admin\Desktop\wechat\WechatAnnualReport\preprocess.py", line 46, in <lambda>
    messages["isGroup"] = messages["NickName"].apply(lambda x: isgroup[x])
                                                               ~~~~~~~^^^
KeyError: '微信团队'
```

**Comment by SphenHe** [comment]
In the pull request " [add features & fix bugs #3](https://github.com/chenyifanthu/WechatAnnualReport/pull/3) ", [Xial-kotori](https://github.com/Xial-kotori) solved this problem, thank you!
